"""公開賽日速覽嵌入 API／payload 測試。"""
from __future__ import annotations

import unittest
from unittest.mock import patch

from fastapi.testclient import TestClient


class RacedayEmbedApiTest(unittest.TestCase):
    def test_html_page_serves_and_allows_j18_frame(self):
        from raceday_embed_api import create_app

        client = TestClient(create_app())
        r = client.get("/embed/raceday")
        self.assertEqual(r.status_code, 200)
        self.assertIn("text/html", r.headers.get("content-type", ""))
        csp = r.headers.get("content-security-policy", "")
        self.assertIn("frame-ancestors", csp)
        self.assertIn("j18.hk", csp)
        self.assertNotIn("x-frame-options", {k.lower() for k in r.headers.keys()})
        self.assertIn("賽日速覽", r.text)
        self.assertIn("/embed/api/default", r.text)
        self.assertIn("horse-radar", r.text)
        self.assertIn("AI 評價", r.text)
        self.assertIn("radarSvg", r.text)

    def test_pc_style_dev_page_is_separate_from_embed(self):
        from raceday_embed_api import create_app

        client = TestClient(create_app())
        pc = client.get("/embed/raceday-pc")
        self.assertEqual(pc.status_code, 200)
        self.assertIn("text/html", pc.headers.get("content-type", ""))
        self.assertIn("賽日速覽", pc.text)
        self.assertIn("綜合走勢", pc.text)
        self.assertIn("推介指數", pc.text)
        self.assertIn('class="sidebar"', pc.text)
        self.assertIn("/embed/api/default", pc.text)
        # 已移除暫不適用的導航／登錄／賠率時間軸
        self.assertNotIn("倍率/指數", pc.text)
        self.assertNotIn("開始賠率", pc.text)
        self.assertNotIn(">登錄<", pc.text)
        # 原嵌入頁未改：仍是右手邊深色卡，不含 PC 整頁側欄
        old = client.get("/embed/raceday")
        self.assertEqual(old.status_code, 200)
        self.assertIn("horse-radar", old.text)
        self.assertNotIn('class="sidebar"', old.text)
        self.assertNotIn("綜合走勢", old.text)

    def test_racecard_board_prototype_serves(self):
        from raceday_embed_api import create_app

        client = TestClient(create_app())
        r = client.get("/embed/racecard")
        self.assertEqual(r.status_code, 200)
        self.assertIn("text/html", r.headers.get("content-type", ""))
        self.assertIn("排位", r.text)
        self.assertIn("nav-back", r.text)
        self.assertIn("返回", r.text)
        self.assertIn("nav-menu-btn", r.text)
        self.assertIn("菜單", r.text)
        self.assertNotIn(">選單<", r.text)
        self.assertIn("topbar-menu", r.text)
        self.assertIn("color: #fff; z-index: 60;", r.text)
        self.assertIn(".topbar-menu {\n      position: absolute;\n      top: calc(100% + 4px);\n      right: 0;\n      z-index: 70;", r.text)
        self.assertIn("bindTopbarMenu", r.text)
        self.assertIn("menu-zoom", r.text)
        self.assertIn("data-zoom-step", r.text)
        self.assertIn("字體", r.text)
        self.assertIn("復原", r.text)
        self.assertIn("menu-theme", r.text)
        self.assertIn('id="themeSwitch"', r.text)
        self.assertIn("j18-racecard-theme", r.text)
        self.assertIn('html[data-theme="dark"]', r.text)
        self.assertIn("深色模式：佈局不變", r.text)
        self.assertIn("toggleTheme", r.text)
        self.assertIn("LIST_ZOOM_MAX", r.text)
        self.assertIn('data-nav="raceDate"', r.text)
        self.assertIn("menuRaceDateBtn", r.text)
        self.assertIn("查看賽期和歷史數據", r.text)
        self.assertIn("menu-date-hint", r.text)
        self.assertIn("menu-date-field", r.text)
        self.assertIn("menu-date-chev", r.text)
        self.assertIn("white-space: nowrap", r.text)
        self.assertIn("WEEKDAY_SHORT", r.text)
        self.assertIn("RACE_FIXTURES", r.text)
        self.assertIn("OVERSEAS_FIXTURES", r.text)
        self.assertIn("openRaceDateCalendar", r.text)
        self.assertIn("syncRaceCalOverlayTop", r.text)
        self.assertIn("cal-month-nav", r.text)
        self.assertIn("raceCalOverlay", r.text)
        self.assertIn("raceCalScopeSwitch", r.text)
        self.assertIn("cal-scope-switch", r.text)
        self.assertIn("香港馬", r.text)
        self.assertIn("外國馬", r.text)
        self.assertIn("previewSelectedFixtureMeta", r.text)
        self.assertIn("loadMeetingForDate", r.text)
        self.assertIn("formatFixtureMetaLine", r.text)
        self.assertIn("resolveRaceStatus", r.text)
        self.assertIn("race-status", r.text)
        self.assertIn("raceStatusLab", r.text)
        self.assertIn("待開賽", r.text)
        self.assertIn("出跑道", r.text)
        self.assertIn("入閘中", r.text)
        self.assertIn("開跑中", r.text)
        self.assertIn("已派彩", r.text)
        self.assertIn("formatRaceInfoLine", r.text)
        self.assertIn("setRaceMetaText", r.text)
        self.assertIn("syncRaceMetaScroll", r.text)
        self.assertIn("raceMetaBounce", r.text)
        self.assertIn('id="raceMetaRun"', r.text)
        self.assertIn('id="raceMetaViewport"', r.text)
        self.assertIn("animation-direction: alternate", r.text)
        self.assertIn('--yellow:', r.text)
        self.assertIn('.race-status[data-status="wait"] .race-status-dot { background: var(--blue); }', r.text)
        self.assertIn('.race-status[data-status="parade"] .race-status-dot { background: var(--green); }', r.text)
        self.assertIn('.race-status[data-status="gate"] .race-status-dot { background: var(--yellow); }', r.text)
        self.assertIn('.race-status[data-status="running"] .race-status-dot {\n      background: var(--red);', r.text)
        self.assertIn('.race-status[data-status="paid"] .race-status-dot { background: var(--orange); }', r.text)
        self.assertIn("capsule-rail", r.text)
        self.assertIn('id="capsuleRail"', r.text)
        self.assertIn("綜合指數", r.text)
        self.assertIn("賽果派彩", r.text)
        self.assertIn("setCapsuleActive", r.text)
        self.assertIn("topIndexPickNos", r.text)
        self.assertIn("bindCapsuleRail", r.text)
        self.assertIn('data-capsule="index"', r.text)
        self.assertIn('data-capsule="payout"', r.text)
        self.assertIn("insight-pin", r.text)
        self.assertIn('id="insightPin"', r.text)
        self.assertIn("time-scrub", r.text)
        self.assertIn("bindTimeScrub", r.text)
        self.assertIn("syncInsightStickyHeight", r.text)
        self.assertIn("--insight-h", r.text)
        self.assertIn("開始賠率", r.text)
        self.assertIn("capsule-status", r.text)
        self.assertIn("capsule-title-stack", r.text)
        self.assertIn("SCRUB_MARK_DEFS", r.text)
        self.assertIn('id="capsulePayoutStatus"', r.text)
        self.assertIn("待派", r.text)
        self.assertIn('.capsule[data-capsule="payout"] .capsule-head-wrap', r.text)
        self.assertIn("payoutFinishNos", r.text)
        self.assertIn("renderPayoutCapNos", r.text)
        self.assertIn("cap-nos-scroll", r.text)
        self.assertIn("cal-legend-col", r.text)
        self.assertIn(".cal-legend[hidden]", r.text)
        self.assertIn("沙田·日馬", r.text)
        self.assertIn("沙田·夜馬", r.text)
        self.assertIn("跑馬地·日馬", r.text)
        self.assertIn("跑馬地·夜馬", r.text)
        self.assertIn("英國", r.text)
        self.assertIn("澳洲", r.text)
        self.assertNotIn("黃昏馬", r.text)
        self.assertIn("歷史排位", r.text)
        self.assertNotIn("今日賽事", r.text)
        self.assertNotIn("關於 J18", r.text)
        self.assertIn("flex-wrap: nowrap", r.text)
        self.assertIn(".race-pills", r.text)
        self.assertIn("overflow-x: auto", r.text)
        self.assertNotIn('class="side r">?</div>', r.text)
        self.assertIn('class="anno"', r.text)
        self.assertIn("anno-lab", r.text)
        self.assertIn("annoMarquee", r.text)
        self.assertIn("公告", r.text)
        self.assertIn("聯繫客服", r.text)
        self.assertIn("pin-odds", r.text)
        self.assertIn("pin-id", r.text)
        self.assertIn("--pin-id", r.text)
        self.assertIn("hno", r.text)
        self.assertIn("has-img", r.text)
        self.assertIn("background-size: contain", r.text)
        self.assertIn("background-color: transparent", r.text)
        self.assertIn("margin: 2px 0 0 1px", r.text)
        self.assertIn(".hrow:not(.head) .cell.pin-id .hno {\n      width: 24px;\n      height: 24px;\n      font-size: 17px;\n      transform: translate(-3px, 2px);\n    }", r.text)
        self.assertIn("padding: 0 26px 0 1px", r.text)
        self.assertIn("margin-top: -1px", r.text)
        self.assertIn("margin-top: -1px", r.text)
        self.assertIn(".hrow:not(.head) {\n      height: 49px;\n    }", r.text)
        self.assertIn("馬號", r.text)
        self.assertIn("檔位", r.text)
        self.assertIn("draw-lab", r.text)
        self.assertIn("draw-no", r.text)
        self.assertIn("draw-sort", r.text)
        self.assertIn(".hno", r.text)
        self.assertIn("color: #fff;\n      font-size: 15px", r.text)
        self.assertIn(".odds .win,\n    .odds .pla {\n      position: relative;\n      display: block;\n      font-size: 14px", r.text)
        self.assertIn(".odds .win { color: var(--text); transform: translateY(-7px); }", r.text)
        self.assertIn(".odds .pla { color: #7b8494; transform: translateY(-4px); }", r.text)
        self.assertIn("font-weight: 400", r.text)
        self.assertIn(".hrow:not(.head) .cell.pin-odds", r.text)
        self.assertIn("draw-flag-col", r.text)
        self.assertIn("align-items: flex-end", r.text)
        self.assertIn("padding: 2px 3px 2px 8px", r.text)
        self.assertIn("row-flag", r.text)
        self.assertIn("transform: translateX(3px)", r.text)
        self.assertIn("cycleRowMark", r.text)
        self.assertIn("M2 1h8v9.2L6 7.4 2 10.2V1z", r.text)
        self.assertIn("draw-sort sortable", r.text)
        self.assertIn("odds-labs", r.text)
        self.assertIn(".draw-no", r.text)
        self.assertIn("border-radius: 50%", r.text)
        self.assertIn("place-items: center", r.text)
        self.assertIn("tabular-nums lining-nums", r.text)
        self.assertIn("translateY(-0.08em)", r.text)
        self.assertIn('<span class="hno"><span>', r.text)
        self.assertIn("letter-spacing: 0", r.text)
        self.assertIn("width: 17px; height: 17px", r.text)
        self.assertIn("--pin-id: 94px", r.text)
        self.assertIn("--pin-odds: 58px", r.text)
        self.assertIn("width: 22px;\n      height: 22px", r.text)
        self.assertIn("width: 21px;\n      height: 21px", r.text)
        self.assertIn("background: var(--nav)", r.text)
        self.assertIn("--head-fs: 13px", r.text)
        self.assertIn("height: 47px", r.text)
        self.assertIn(".hname {\n      display: block;\n      font-size: 13px; font-weight: 400", r.text)
        self.assertIn("text-align: left", r.text)
        self.assertIn("padding: 0 26px 0 1px", r.text)
        self.assertIn("transform: translateX(-5px)", r.text)
        self.assertIn("width: calc(100% + 5px)", r.text)
        self.assertIn("舊 52px 會讓四字馬名被截斷", r.text)
        self.assertIn("僅馬名左移 5px", r.text)
        self.assertIn("grid-template-columns: 33px 22px 15px", r.text)
        self.assertIn("jt-ini", r.text)
        self.assertIn(".jt-ini .j-ini,\n    .jt-ini .t-ini {\n      display: block;\n      font-size: 12px;", r.text)
        self.assertIn(".jt-ini .t-ini { transform: translateY(1px); }", r.text)
        self.assertIn("jockeyInitial", r.text)
        self.assertIn("trainerInitial", r.text)
        self.assertIn("jtInitialsHtml", r.text)
        self.assertIn("grid-template-rows: 31px minmax(0, 1fr)", r.text)
        self.assertIn("color: #111", r.text)
        self.assertIn(".sortable.on { color: #2c5f8a; }", r.text)
        self.assertNotIn("color: #6b7380", r.text)
        self.assertIn("font-size: var(--head-fs); font-weight: 400", r.text)
        self.assertIn(".head-static {\n      display: block;\n      font-size: var(--head-fs); font-weight: 400", r.text)
        self.assertIn("color: inherit; cursor: default; user-select: none;", r.text)
        self.assertIn('html[data-theme="dark"] .head-static', r.text)
        self.assertIn('html[data-theme="dark"] .hrow.head .cell.sort-on', r.text)
        self.assertIn("排序中表頭：深色藍底＋淺字", r.text)
        self.assertIn('html[data-theme="dark"] .draw-no', r.text)
        self.assertIn("檔位圓圈：深底淺字", r.text)
        self.assertIn("菜單浮層：抬高底色＋亮邊＋陰影", r.text)
        self.assertIn("rgba(210, 222, 236, .28)", r.text)
        self.assertIn("燕尾標整行：呼應淺色黃／綠", r.text)
        self.assertIn("#6b4f1c", r.text)
        self.assertIn("#1f5c3e", r.text)
        self.assertIn(".scroll-col.num {\n      font-variant-numeric: tabular-nums;\n      font-weight: 400", r.text)
        self.assertIn(".odds {\n      display: flex;\n      flex-direction: column;\n      align-items: flex-end;\n      justify-content: flex-end;\n      gap: 2px", r.text)
        self.assertIn("ensureOddsTickDemo", r.text)
        self.assertIn("oddsTickHtml", r.text)
        self.assertIn("oddsLineHtml", r.text)
        self.assertIn('class="od-tick ', r.text)
        self.assertIn("left: 100%", r.text)
        self.assertIn("winTick", r.text)
        self.assertIn("▼", r.text)
        self.assertIn("▲", r.text)
        self.assertIn("odTickBreath", r.text)
        self.assertIn("simulateOddsTickRefresh", r.text)
        self.assertIn('data-nav="demoOddsTick"', r.text)
        self.assertIn('demoOddsTick") === "1"', r.text)
        self.assertNotIn("od-tick.flat", r.text)
        self.assertNotIn("pin-draw", r.text)
        self.assertNotIn("draw-dot", r.text)
        self.assertNotIn("draw-pct", r.text)
        self.assertNotIn("--pin-draw", r.text)
        self.assertIn("fmtDrawPct", r.text)
        self.assertIn("DRAW_WIN_DEMO", r.text)
        self.assertIn("10.8", r.text)
        self.assertIn("獨贏", r.text)
        self.assertIn("位置", r.text)
        self.assertIn("負磅", r.text)
        self.assertIn('key: "water"', r.text)
        self.assertIn('key: "flow"', r.text)
        self.assertIn('label: "水位"', r.text)
        self.assertIn('id="waterSheet"', r.text)
        self.assertIn("水位彈窗", r.text)
        self.assertIn("openWaterSheet", r.text)
        self.assertIn("fillWaterSheet", r.text)
        self.assertIn("bindWaterSheetOpens", r.text)
        self.assertIn("waterHourLabels", r.text)
        self.assertIn("waterHourSample", r.text)
        self.assertIn("wpWater", r.text)
        self.assertIn("wpFlow", r.text)
        self.assertIn('wh-line wp', r.text)
        self.assertIn("上獨贏／中位置／下 WP", r.text)
        self.assertIn("日後接 API，不在此混合推算", r.text)
        self.assertIn("water-board", r.text)
        self.assertIn("wh-line", r.text)
        self.assertIn("wh-metric", r.text)
        self.assertIn("wh-arr", r.text)
        self.assertIn("waterTrendDir", r.text)
        self.assertIn("bindWaterCrossFocus", r.text)
        self.assertIn("applyWaterCrossFocus", r.text)
        self.assertIn("clearWaterCrossFocusState", r.text)
        self.assertIn("is-wh-cross-cell", r.text)
        self.assertIn("data-wh-col", r.text)
        self.assertIn(".water-row.is-wh-cross-row .water-pin", r.text)
        self.assertIn("十字高亮：沿用水位頂欄綠系", r.text)
        self.assertIn("#dce9e2", r.text)
        self.assertIn("#a8c9b6", r.text)
        self.assertIn(".water-row.is-wh-cross-row .wh-arr:not(.none)", r.text)
        self.assertIn("點格高亮後見水位升降", r.text)
        self.assertIn("waterMetricHtml", r.text)
        self.assertIn('waterMetricHtml("fv"', r.text)
        self.assertIn("no-arr", r.text)
        self.assertIn("--wh-arr-w:", r.text)
        self.assertIn("水位箭頭在數字前", r.text)
        self.assertIn("高於更早時段（升）", r.text)
        self.assertIn("低於更早時段（降）", r.text)
        self.assertIn("時段由近到遠", r.text)
        self.assertIn("wp-jt-col", r.text)
        self.assertIn("wp-jname", r.text)
        self.assertIn("wp-tname", r.text)
        self.assertIn("shortWaterJtName", r.text)
        self.assertIn("water-lock", r.text)
        self.assertIn("wp-stack", r.text)
        self.assertIn("--wh-pin-w: 73px", r.text)
        self.assertIn("--wh-odds-w: 37px", r.text)
        self.assertIn("transform: translateX(-5px)", r.text)
        self.assertIn("odTickBreathWp", r.text)
        self.assertIn("top: calc(var(--wh-num-fs) * var(--wh-num-lh) / 2)", r.text)
        self.assertIn(".wp-odds .win.hot,", r.text)
        self.assertIn(".wp-odds .od-tick", r.text)
        self.assertIn('oddsLineHtml("win", r.scratched ? null : r.win', r.text)
        self.assertIn('"↖"', r.text)
        self.assertIn('"↙"', r.text)
        self.assertIn("--wh-col-w: 54px", r.text)
        self.assertIn("--wh-num-fs: 14px", r.text)
        self.assertIn("height: var(--wh-line-h)", r.text)
        self.assertIn('pin-lab">賠率', r.text)
        self.assertNotIn("wp-tag", r.text)
        self.assertNotIn(">騎</span>", r.text)
        self.assertNotIn(">練</span>", r.text)
        self.assertIn(".water-pin .hno {\n      flex: 0 0 auto;\n      display: grid;\n      place-items: center;\n      place-content: center;\n      width: 22px;\n      height: 22px;", r.text)
        self.assertIn("font-size: 15px;", r.text)
        self.assertIn("#boardMain,\n    #waterSheetZoom", r.text)
        self.assertIn('id="waterSheetZoom"', r.text)
        self.assertIn("closeMenuIfOutside", r.text)
        self.assertIn('data-open="water"', r.text)
        self.assertIn('c.key === "water" || c.key === "flow"', r.text)
        self.assertIn("水位／流量詳情", r.text)
        self.assertIn("is-water-open", r.text)
        self.assertIn("syncWaterSheetTop", r.text)
        self.assertIn('label: "流量"', r.text)
        self.assertIn("ensureWaterFlowDemo", r.text)
        self.assertIn("ensureWaterFlowTickDemo", r.text)
        self.assertIn("winWaterTick", r.text)
        self.assertIn("winFlowTick", r.text)
        self.assertIn("wpLineHtml", r.text)
        self.assertIn("ensureRunStyleDemo", r.text)
        self.assertIn("cellRunStyle", r.text)
        self.assertIn("runStyleChipHtml", r.text)
        self.assertIn("RUN_STYLE_SHORT", r.text)
        self.assertIn("rs-chip", r.text)
        self.assertIn('.rs-chip.lead { background: #3d5a80; }', r.text)
        self.assertIn('ch: "前領"', r.text)
        self.assertIn('ch: "跟前"', r.text)
        self.assertIn('ch: "中置"', r.text)
        self.assertIn('ch: "後上"', r.text)
        self.assertIn("padding: 0 26px 0 1px", r.text)
        self.assertIn("兩字全稱角標", r.text)
        self.assertIn("rs-marks", r.text)
        self.assertIn("rs-tri", r.text)
        self.assertIn("前領", r.text)
        self.assertIn("跟前", r.text)
        self.assertIn("中置", r.text)
        self.assertIn("後上", r.text)
        self.assertIn("cellWinPlacePair", r.text)
        self.assertIn("winWater", r.text)
        self.assertIn("placeWater", r.text)
        self.assertIn("winFlow", r.text)
        self.assertIn("placeFlow", r.text)
        self.assertIn("fmtFlow", r.text)
        self.assertIn('class="wp"', r.text)
        self.assertIn(".scroll-col .wp .w,\n    .scroll-col .wp .p {\n      position: relative;\n      display: block;\n      font-size: 14px", r.text)
        self.assertIn(".scroll-col .wp .w {\n      color: var(--text);\n      transform: translateY(-8px)", r.text)
        self.assertIn(".scroll-col .wp .p {\n      color: #7b8494;\n      transform: translateY(-5px)", r.text)
        self.assertIn("transform: translateY(-7px)", r.text)
        self.assertIn("transform: translateY(-4px)", r.text)
        self.assertIn("transform: translateY(-8px)", r.text)
        self.assertIn("transform: translateY(-5px)", r.text)
        self.assertNotIn(".odds .pla { font-size: 14px; font-weight: 400; color: #7b8494; transform: translateY(-3px); }", r.text)
        self.assertIn(".scroll-col:has(.wp)", r.text)
        self.assertIn("padStart(2, \"0\")", r.text)
        self.assertIn("fmtDelta", r.text)
        self.assertIn("hwDeltaOf", r.text)
        self.assertIn("cellStackedMainDelta", r.text)
        self.assertIn("delta-pos", r.text)
        self.assertIn("delta-neg", r.text)
        self.assertIn(".scroll-col .v.stacked .sub.delta {\n      font-size: 12px;\n      font-weight: 400", r.text)
        self.assertIn("ensureHwDeltaDemo", r.text)
        self.assertIn("預計", r.text)
        self.assertIn("最佳\\n時間", r.text)
        self.assertIn('key: "bestTime"', r.text)
        self.assertIn("ensureBestTimeDemo", r.text)
        self.assertIn("fmtRaceTimeCs", r.text)
        self.assertIn("1:10.17", r.text)
        self.assertIn("近六", r.text)
        self.assertIn("賽績", r.text)
        self.assertIn("班次", r.text)
        self.assertIn("近六賽績\\n班次升降", r.text)
        self.assertIn("ensureClass6Demo", r.text)
        self.assertIn("cellForm6", r.text)
        self.assertIn("fc-seg", r.text)
        self.assertIn("fc-num", r.text)
        self.assertIn("form-class", r.text)
        self.assertNotIn('key: "class6"', r.text)
        self.assertIn("入圍數｜%", r.text)
        self.assertIn('cls: "scroll-col num end"', r.text)
        self.assertIn(".scroll-col.end {\n      justify-content: flex-end;\n      text-align: right", r.text)
        self.assertIn("ensurePlaceInDemo", r.text)
        self.assertIn("fmtPlaceInLeft", r.text)
        self.assertIn("cellPlaceIn", r.text)
        self.assertIn("16/32｜50%", r.text)
        self.assertIn("placeInTotal", r.text)
        self.assertIn("歷季", r.text)
        self.assertIn("parseCareerRecord", r.text)
        self.assertIn("fmtCareer", r.text)
        self.assertIn('key: "career"', r.text)
        self.assertIn("同班賽", r.text)
        self.assertIn("同場", r.text)
        self.assertIn("ensureSameTrackDemo", r.text)
        self.assertIn("fmtRecordTriple", r.text)
        self.assertIn("cellRecordTriple", r.text)
        self.assertIn("23（6-4-5）", r.text)
        self.assertIn("sameCourseDist", r.text)
        self.assertIn("sameDist", r.text)
        self.assertIn("ensureLayoffLastOddsDemo", r.text)
        self.assertIn("fmtLayoff", r.text)
        self.assertIn("lastWinOdds", r.text)
        self.assertIn("lastPlaceOdds", r.text)
        self.assertIn("fmtLastOdds", r.text)
        self.assertIn("同程", r.text)
        self.assertIn("久休", r.text)
        self.assertIn("上仗", r.text)
        self.assertIn("裝備", r.text)
        self.assertIn("今季獎金", r.text)
        self.assertIn("總獎金", r.text)
        self.assertIn("placeIn", r.text)
        self.assertIn("prizePair", r.text)
        self.assertIn("runStyle", r.text)
        self.assertNotIn("賽前\n綜合分", r.text)
        self.assertNotIn('"key": "score"', r.text)
        self.assertNotIn('key: "score"', r.text)
        self.assertNotIn('key: "value"', r.text)
        self.assertNotIn('key: "gold2"', r.text)
        self.assertNotIn('label: "近績"', r.text)
        self.assertNotIn('label: "配備"', r.text)
        self.assertIn("外祖父", r.text)
        self.assertIn("左鎖", r.text)
        self.assertIn("lock-cluster", r.text)
        self.assertIn("horse-sheet", r.text)
        self.assertIn("openHorseSheet", r.text)
        self.assertIn("closeHorseSheet", r.text)
        self.assertIn("horseSheetClose", r.text)
        self.assertIn('data-no="', r.text)
        self.assertIn("board-shell", r.text)
        self.assertIn("board-main", r.text)
        self.assertIn("board-horses", r.text)
        self.assertIn("board-head-pin", r.text)
        self.assertIn("board-head-x", r.text)
        self.assertIn("syncHeadScrollLeft", r.text)
        self.assertIn("bindHorseHeadScroll", r.text)
        self.assertIn("overflow-y: clip", r.text)
        self.assertNotIn("translate3d(", r.text)
        self.assertNotIn("board-lock-pin", r.text)
        self.assertNotIn("syncHorseHeadPin", r.text)
        self.assertNotIn("is-vpinned", r.text)
        self.assertNotIn("head-scroll-track", r.text)
        self.assertNotIn("syncHeadScrollTrack", r.text)
        self.assertIn("qin-panel", r.text)
        self.assertIn("qin-tbl", r.text)
        self.assertIn("qin-x", r.text)
        self.assertIn("overscroll-behavior: none", r.text)
        self.assertIn("-webkit-overflow-scrolling: touch", r.text)
        self.assertIn("bindQinOverscrollGuard", r.text)
        self.assertIn("startWrapInertia", r.text)
        self.assertIn("stopWrapInertia", r.text)
        self.assertIn("sampleFingerVel", r.text)
        self.assertIn("wrap.scrollTop -= deltaY", r.text)
        self.assertNotIn("handedOff", r.text)
        self.assertIn("qin-rh", r.text)
        self.assertIn("qin-ch", r.text)
        self.assertIn("data-qin-key", r.text)
        self.assertIn("is-qin-focus", r.text)
        self.assertIn("bindQinPairFocus", r.text)
        self.assertIn("setQinPairFocus", r.text)
        self.assertIn("qinFocusPulse", r.text)
        self.assertIn("prefers-reduced-motion", r.text)
        self.assertIn("框外 outline 呼吸", r.text)
        self.assertIn("outline-offset", r.text)
        self.assertNotIn("inset 0 0 0 2px #ff9a1a", r.text)
        self.assertIn("qin-mode-switch", r.text)
        self.assertIn("qin-mode-switch-lg", r.text)
        self.assertIn("qin-legend-actions", r.text)
        self.assertIn("renderQinModeSwitchBtn", r.text)
        self.assertIn("qin-switch-cell", r.text)
        self.assertIn("qin-sw-thumb", r.text)
        self.assertIn("qin-sw-lab", r.text)
        self.assertIn("data-qin-mode", r.text)
        self.assertIn("data-qin-side", r.text)
        self.assertIn("var(--orange)", r.text)
        self.assertIn("renderQinModeSwitch", r.text)
        self.assertNotIn("qin-mode-btn", r.text)
        self.assertNotIn("qin-title-sub", r.text)
        self.assertNotIn("qin-title-stack", r.text)
        self.assertNotIn("renderQinTitle", r.text)
        self.assertNotIn("qin-mode-cell", r.text)
        self.assertIn("setQinMode", r.text)
        self.assertIn("refreshQinPanel", r.text)
        self.assertIn("就地改數值", r.text)
        self.assertIn("el.board.scrollTop = boardSt", r.text)
        self.assertIn("bindQinModeSwitch", r.text)
        self.assertIn("toggleQinMode", r.text)
        self.assertIn("整塊角標或圖例右側大號開關，任意點擊均切換", r.text)
        self.assertIn("synthQplOdds", r.text)
        self.assertIn("連贏位置", r.text)
        self.assertIn("正Q", r.text)
        self.assertIn("位置Q", r.text)
        self.assertIn("qin-idx-lab", r.text)
        self.assertIn("qin-idx-txt", r.text)
        self.assertIn("qin-idx-no", r.text)
        self.assertIn("qin-idx-inner", r.text)
        self.assertIn("writing-mode: vertical-rl", r.text)
        self.assertIn(">指數</span>", r.text)
        self.assertNotIn(">指數</th>", r.text)
        self.assertIn('scope="row"', r.text)
        self.assertIn(".qin-tbl .qin-rh {\n      position: sticky", r.text)
        self.assertIn(".qin-tbl .qin-ch {\n      position: sticky", r.text)
        self.assertIn('colspan="2"', r.text)
        self.assertNotIn("連/指", r.text)
        self.assertIn("上三角", r.text)
        self.assertIn("下三角", r.text)
        self.assertIn("idx-cell", r.text)
        self.assertIn(".qin-tbl .qin-c.idx-cell.idx-r", r.text)
        self.assertIn(".qin-tbl .qin-c.idx-cell.idx-g", r.text)
        self.assertIn(".qin-tbl .qin-c.idx-cell.idx-b", r.text)
        self.assertIn("background: #e74c3c", r.text)
        self.assertIn("連贏賠率", r.text)
        self.assertIn("連贏指數", r.text)
        self.assertIn("synthQinOdds", r.text)
        self.assertIn("buildQinPairs", r.text)
        self.assertIn("qinPairInvolvesScratch", r.text)
        self.assertIn("data-qin-scratch", r.text)
        self.assertIn("qin-c.scratch", r.text)
        self.assertIn("QIN_FIT_N", r.text)
        self.assertIn("const QIN_FIT_N = 14", r.text)
        self.assertIn("QIN_MAX_N", r.text)
        self.assertNotIn("QIN_MIN_CELL", r.text)
        self.assertIn("fitQinTableWidths", r.text)
        self.assertNotIn("const titleW0 = 40", r.text)
        self.assertIn("qin-col-rh", r.text)
        self.assertIn("qin-col-c", r.text)
        self.assertIn("<colgroup>", r.text)
        self.assertIn("const titleW = cell", r.text)
        self.assertIn("n <= QIN_FIT_N", r.text)
        self.assertIn("avail / (QIN_FIT_N + 1)", r.text)
        self.assertIn("ensureQinDemo20Race", r.text)
        self.assertIn("ensureRace9Has14Runners", r.text)
        self.assertIn("demoPad14", r.text)
        self.assertIn("ensureRace8Has8Runners", r.text)
        self.assertIn("demoTrim8", r.text)
        self.assertIn("ensureRace7Has6Runners", r.text)
        self.assertIn("demoTrim6", r.text)
        self.assertIn("ensureRace6Has10WithScratch7", r.text)
        self.assertIn("demoTrim10Scratch7", r.text)
        self.assertIn("二十駒演示", r.text)
        self.assertIn("board-x", r.text)
        self.assertIn("row-flag", r.text)
        self.assertIn("draw-flag-col", r.text)
        self.assertIn("cycleRowMark", r.text)
        self.assertIn("mark-1", r.text)
        self.assertIn("mark-2", r.text)
        self.assertNotIn("qinPreviewN", r.text)
        self.assertNotIn("qin-preview", r.text)
        self.assertNotIn("qin-dense", r.text)
        self.assertNotIn("qinIdxToggle", r.text)
        self.assertNotIn("qin-idx-block", r.text)
        self.assertNotIn("date-row", r.text)
        self.assertNotIn("▾", r.text)
        self.assertNotIn('class="hint"', r.text)
        self.assertNotIn("資料截自馬會", r.text)
        self.assertIn("堅多福", r.text)
        self.assertIn('"win":3.4', r.text)
        self.assertIn('"place":1.5', r.text)
        self.assertIn('"win":13', r.text)
        self.assertIn("fmtOdds", r.text)
        self.assertNotIn("尚未開出", r.text)
        self.assertIn("跑馬地", r.text)
        self.assertIn("騎師", r.text)
        self.assertIn("練馬師", r.text)
        self.assertIn("splitNameAllow", r.text)
        self.assertIn("v stacked", r.text)
        self.assertIn("v.stacked .sub", r.text)
        self.assertIn("p.delta", r.text)
        self.assertIn('c.key === "jockey"', r.text)
        self.assertIn("font: inherit", r.text)
        self.assertIn("fitScrollColWidths", r.text)
        self.assertIn("applyMeeting", r.text)
        self.assertIn("COL_FIT", r.text)
        self.assertIn("dataToRulePx: 2", r.text)
        self.assertIn("--scroll-col-gap: 2px", r.text)
        self.assertIn("width: max-content", r.text)
        self.assertNotIn("min-width: 54px", r.text)
        self.assertNotIn(".scroll-col.sm", r.text)
        self.assertIn("var(--scroll-col-gap)", r.text)
        self.assertNotIn("top: 6px; bottom: 6px", r.text)
        self.assertIn("周俊樂 (-2)", r.text)
        self.assertIn("南風讓賽", r.text)
        self.assertNotIn("辣得金", r.text)
        self.assertNotIn("scrollHeadClip", r.text)
        self.assertIn("head-static", r.text)
        self.assertIn("sort-ico", r.text)
        self.assertNotIn('data-sort="name"', r.text)
        self.assertNotIn('data-sort="place"', r.text)
        self.assertNotIn('data-sort="win"', r.text)
        self.assertIn('data-sort="draw"', r.text)
        self.assertNotIn("tabbar", r.text)
        self.assertNotIn("主選單", r.text)
        self.assertNotIn("名家", r.text)
        # 不取代原有賽日嵌入頁
        old = client.get("/embed/raceday")
        self.assertNotIn("pin-odds", old.text)

    def test_health_and_default_empty(self):
        from raceday_embed_api import create_app

        client = TestClient(create_app())
        h = client.get("/embed/api/health")
        self.assertEqual(h.status_code, 200)
        self.assertEqual(h.json().get("service"), "j18-raceday-embed")

        d = client.get("/embed/api/default")
        self.assertEqual(d.status_code, 200)
        body = d.json()
        self.assertTrue(body.get("ok"))
        self.assertIn("races", body)

    def test_race_not_found(self):
        from raceday_embed_api import create_app

        with patch(
            "raceday_embed_payload.build_race_prediction",
            return_value={"ok": False, "error": "no_prediction", "race_id": "x"},
        ):
            # patch where used inside build_public_race_view
            with patch(
                "raceday_embed_payload.build_public_race_view",
                return_value={"ok": False, "error": "no_prediction", "race_id": "x"},
            ):
                client = TestClient(create_app())
                r = client.get("/embed/api/races/NOPE")
                self.assertEqual(r.status_code, 404)

    def test_mounted_on_ad_api(self):
        import ad_api

        client = TestClient(ad_api.app)
        r = client.get("/embed/raceday")
        self.assertEqual(r.status_code, 200)
        self.assertIn("賽日速覽", r.text)

    def test_public_race_view_includes_fused(self):
        from raceday_embed_payload import build_public_race_view

        fake_base = {
            "ok": True,
            "race_id": "20260906ST01",
            "race": {
                "racing_date": "2026-09-06",
                "course": "ST",
                "race_num": 1,
                "n_runners": 2,
                "expected_pace": "快",
            },
            "meta": {"match_rate": 0.9, "avg_model_coverage": 0.8, "provisional": False},
            "picks": {
                "win": [{"horse_no": 1, "horse_name": "甲", "model_win_prob_pct": 60}],
                "place": [
                    {"horse_no": 1, "horse_name": "甲", "model_win_prob_pct": 60},
                    {"horse_no": 2, "horse_name": "乙", "model_win_prob_pct": 40},
                ],
            },
            "runners": [
                {
                    "horse_no": 1,
                    "horse_name": "甲",
                    "draw": 1,
                    "jockey": "J1",
                    "trainer": "T1",
                    "pred_rank": 1,
                    "total_score": 5.55,
                    "model_win_prob": 0.6,
                    "model_win_prob_pct": 60.0,
                    "factors": {
                        "jockey": 1.0,
                        "trainer": 0.8,
                        "synergy": 0.9,
                        "draw": 0.5,
                        "form": 1.2,
                        "pace": 0.7,
                        "speed": 1.1,
                        "speed_guide": 0.4,
                    },
                    "ai": {"ai_score": 0.8, "confidence": 0.9, "ai_combo": 0.72, "summary": "穩"},
                },
                {
                    "horse_no": 2,
                    "horse_name": "乙",
                    "draw": 2,
                    "jockey": "J2",
                    "trainer": "T2",
                    "pred_rank": 2,
                    "total_score": 4.10,
                    "model_win_prob": 0.4,
                    "model_win_prob_pct": 40.0,
                    "factors": {
                        "jockey": 0.2,
                        "trainer": 0.3,
                        "synergy": 0.1,
                        "draw": 0.9,
                        "form": 0.4,
                        "pace": 0.2,
                        "speed": 0.3,
                        "speed_guide": 0.8,
                    },
                    "ai": {"ai_score": 0.2, "confidence": 0.5, "ai_combo": 0.1, "summary": ""},
                },
            ],
        }
        with patch(
            "raceday_embed_payload.build_race_prediction", return_value=fake_base
        ):
            out = build_public_race_view("20260906ST01")
        self.assertTrue(out["ok"])
        self.assertIn("fused", out["picks"])
        self.assertEqual(out["race"]["course_label"], "沙田")
        self.assertEqual(len(out["runners"]), 2)
        self.assertIn("fused_share_pct", out["runners"][0])
        r0 = out["runners"][0]
        self.assertIn("radar", r0)
        self.assertEqual(len(r0["radar"]["labels"]), 8)
        self.assertEqual(len(r0["radar"]["values"]), 8)
        self.assertEqual(r0["ai_combo"], 0.72)
        self.assertEqual(r0["ai_summary"], "穩")
        self.assertIn("radar_axes", out)

    def test_json_safe_handles_numpy(self):
        import numpy as np

        from raceday_embed_payload import _json_safe

        raw = {
            "a": np.float64(1.25),
            "b": np.int64(3),
            "c": [np.float32(0.5), {"d": np.bool_(True)}],
        }
        out = _json_safe(raw)
        self.assertEqual(out["a"], 1.25)
        self.assertEqual(out["b"], 3)
        self.assertEqual(out["c"][0], 0.5)
        self.assertIs(out["c"][1]["d"], True)
        import json

        json.dumps(out)  # must not raise


if __name__ == "__main__":
    unittest.main()
